engines:
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseMethodName:
        enabled: false
      Design/TooManyMethods:
        enabled: false
  phpcodesniffer:
    enabled: true
    checks:
      PSR1 Methods CamelCapsMethodName NotCamelCaps:
        enabled: false
ratings:
  paths:
  - "**.php"
  - "**.module"
  - "**.inc"
exclude_paths:
- spec/*
